### ISSUE TITLE
Errors on Installation with 3.4.2

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#117]
> <a href="https://github.com/hostianer"><img src="https://avatars.githubusercontent.com/u/8193345?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/39) by @hostianer
Monday Jan 26, 2015 at 14:57 GMT

MAMP Pro PHP 5.6.2, local on OSX.
Also tested with PHP 5.5.18

Version 3.4.0 is working without problems.

If i go to the /install.php i`m getting these errors:
```
Notice: Undefined index: HTTP_X_FORWARDED_HOST in /Applications/MAMP/htdocs/pixelianer/system/modules/core/library/Contao/Environment.php on line 302 

Notice: Undefined index: SSL_SESSION_ID in /Applications/MAMP/htdocs/pixelianer/system/modules/core/library/Contao/Environment.php on line 313 

Notice: Undefined index: HTTPS in /Applications/MAMP/htdocs/pixelianer/system/modules/core/library/Contao/Environment.php on line 313 

Notice: Undefined index: HTTPS in /Applications/MAMP/htdocs/pixelianer/system/modules/core/library/Contao/Environment.php on line 313 

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/pixelianer/system/modules/core/library/Contao/Environment.php:302) in system/modules/core/library/Contao/Controller.php on line 2125 
#0 [internal function]: __error(2, 'Cannot modify h...', '/Applications/M...', 2125, Array) 
#1 system/modules/core/library/Contao/Controller.php(2125): header('HTTP/1.1 303 Se...') 
#2 system/modules/core/controllers/BackendInstall.php(315): Contao\Controller::reload() 
#3 system/modules/core/controllers/BackendInstall.php(80): Contao\BackendInstall->acceptLicense() 
#4 contao/install.php(24): Contao\BackendInstall->run() 
#5 {main} 

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/pixelianer/system/modules/core/library/Contao/Environment.php:302) in system/modules/core/library/Contao/Controller.php on line 2126 
#0 [internal function]: __error(2, 'Cannot modify h...', '/Applications/M...', 2126, Array) 
#1 system/modules/core/library/Contao/Controller.php(2126): header('Location: http:...') 
#2 system/modules/core/controllers/BackendInstall.php(315): Contao\Controller::reload() 
#3 system/modules/core/controllers/BackendInstall.php(80): Contao\BackendInstall->acceptLicense() 
#4 contao/install.php(24): Contao\BackendInstall->run() 
#5 {main}  
```

**Comment by importer** [comment]
> <a href="https://github.com/xchs"><img src="https://avatars.githubusercontent.com/u/1218766?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @xchs
Monday Jan 26, 2015 at 15:11 GMT

This has already been fixed (see https://github.com/contao/core/issues/7593).
