### ISSUE TITLE
Search indexing – Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#1452]
We are experiencing the following duplicate search index entry error in Contao 4.4.16:

```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO tl_search (`tstamp`, `url`, `title`, `protected`, `filesize`, `groups`, `pid`, `language`, `text`, `checksum`) VALUES (1522468713, 'https://domain.tld/de/veranstaltungen/alle-veranstaltungen.html?bpid=996811229&nlid=1284351984&mid=993144775&chk=iDTWRSPhxO', 'alle Veranstaltungen', '', '0.89', 0, '313', 'de', 'alle Veranstaltungen Redirecting to https://domain.tld/de/veranstaltungen/alle-veranstaltungen.html?bpid=996811229&nlid=1284351984&mid=993144775&chk=iDTWRSPhxO&date=31.03.2018.', 'd09c1d6c9191fe715ed3b53f26dbf091')':

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://domain.tld/de/veranstaltungen/alle-veransta' for key 'url'
#15 vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php(70): convertException
#14 vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(176): wrapException
#13 vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(150): driverExceptionDuringQuery
#12 vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(915): executeQuery
#11 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php(284): query
#10 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php(257): execute
#9 vendor/contao/core-bundle/src/Resources/contao/library/Contao/Search.php(227): indexPage
#8 vendor/contao/core-bundle/src/Resources/contao/classes/Frontend.php(669): indexPageIfApplicable
#7 vendor/contao/core-bundle/src/Framework/Adapter.php(47): __call
#6 vendor/contao/core-bundle/src/EventListener/AddToSearchIndexListener.php(74): onKernelTerminate
#5 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): doDispatch
#4 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): dispatch
#3 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(88): terminate
#2 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(167): terminate
#1 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php(218): terminate
#0 web/app.php(32): null
```

One special thing on this page is a frontend module which adds the `date` parameter if not present. The other URL parameters seem to by just an addition from some newsletter campaign or something like that. The content generated by this module is also dynamic as its taken from the external API service, yet it's wrapped in `block_unsearchable`.

I am unable to track down the real issue here as the whole search index logic is not fully understandable for me. Could this issue be perhaps caused by a bug? Or maybe indexer does not support this redirect case?

Or maybe that's happening because we (probably) cloned the legacy database and just changed the page aliases? So that the `veranstaltungen/alle-veranstaltungen` alias was taken from page ID 123 in favour of 456? This also brings me to the question why is there no search index update for `onsubmit_callback` within `tl_page`? There is already one for `ondelete_callback` though.

/cc @Toflar

**Comment by fritzmg** [comment]
> Or maybe that's happening because we (probably) cloned the legacy database and just changed the page aliases?

Did you rebuild the search index afterwards?

**Comment by qzminski** [comment]
I can't confirm that but still maybe this error/case should be caught/considered in core?

**Comment by fritzmg** [comment]
Can you reproduce it in a fresh installation by switching the alias of two pages? (I am not sure if you have to change the content too - or may be you shouldn't.)

**Comment by Toflar** [comment]
I think this issue is fixed with https://github.com/contao/core-bundle/pull/1522. It seems to be directly related because I have the exact same amount of exceptions.

**Comment by leofeyer** [comment]
Then I'll close the ticket for now. If it turns out the issue does not get fixed by #1522, please let me know and I'll re-open.

**Comment by qzminski** [comment]
I would like to re-open this issue. The problem may affect various cases but I found at least one example that can be reproduced. So imagine the site structure like this:

```
– Website root (domain.tld)
–– Subpage 1 (subpage-1.html)
–– Subpage 2 (subpage-2.html)
```

Now when you enter the website directly under `domain.tld` you get the `Subpage 1` content displayed. The page is indexed under `domain.tld` URL and all is fine.

However when you unpublish `Subpage 1` and visit the website once again, you will get the `Subpage 2` content displayed under the very same URL – `domain.tld`. And here `Contao\Search::indexPage` has some troubles:

1. First, it prepares all the page content.
2. Then, it checks in the database whether this page and its content exists under requested URL. This block is completely skipped because `$arrSet['pid']` (which is equivalent to current page ID) is not found in the database – it would be found for `Subpage 1` but not for `Subpage 2` (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Search.php#L181-L207).
3. Next, it tries to find the entry in search index that matches current URL and page. Again nothing is found, although URL matches but page ID does not! So it simply tries to add another entry and here is where the unique constraint violation exception of `tl_search.url` is thrown (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Search.php#L209-L229).

It's not that easy to spot this one (Sentry FTW!) as the exception is not thrown to the frontend because indexing happens in `Contao\CoreBundle\EventListener\AddToSearchIndexListener` which listens to `kernel.terminate` where exceptions are only logged.

I am not 100% sure how to fix this but since `tl_search.url` became a unique index in the database, we should check explicitly for it and not for the combination with `pid`:

```diff
-$objIndex = $objDatabase->prepare("SELECT id FROM tl_search WHERE url=? AND pid=?")
-                        ->limit(1)
-                        ->execute($arrSet['url'], $arrSet['pid']);
+$objIndex = $objDatabase->prepare("SELECT id FROM tl_search WHERE url=?")
+                        ->limit(1)
+                        ->execute($arrSet['url']);

// Add the page to the tl_search table
if ($objIndex->numRows)
{
    $objDatabase->prepare("UPDATE tl_search %s WHERE id=?")
                ->set($arrSet)
                ->execute($objIndex->id);

    $intInsertId = $objIndex->id;
}
else
{
    $objInsertStmt = $objDatabase->prepare("INSERT INTO tl_search %s")
                                 ->set($arrSet)
                                 ->execute();

    $intInsertId = $objInsertStmt->insertId;
}
```

PS. I haven't still figured out why the similar error happens for subpages (see error log in my first issue description) but I think we should first fix this one.

**Comment by fritzmg** [comment]
This is odd. At one point it was implemented, that you get redirected to the first page's URL, if the alias of the first page is not `index`. This is no happening anymore.

**Comment by Toflar** [comment]
To me the change is quite obvious. The page id does not matter. The URL is relevant. In fact it's the very same logic as for a cache entry: Relevant are the URI and the Vary header (which we currently do not check here, we could though).

**Comment by qzminski** [comment]
In addition to @fritzmg point, even if we restore back the previous functionality I think the error would still remain e.g. for the case where you would remove `Subpage A` and then change alias of `Subpage B` to what was for `Subpage A`.

**Comment by leofeyer** [comment]
@qzminski Good job debugging this! 👍
